//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmicantaratXF.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmicantaratXF.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dip (meters).
        /// </summary>
        public static string dip {
            get {
                return ResourceManager.GetString("dip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=UTF-8&quot; http-equiv=&quot;content-type&quot;&gt;
        ///    &lt;style&gt;
        ///      img {
        ///  		width:70%;
        ///
        ///        text-align: center;
        ///  		height:auto;
        ///			}
        ///      p,h1,h2
        ///      {
        ///        font-family: Cambria;
        ///      }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;navigation astronomique pratique&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1&gt;La navigation astronomique - Practice - Part 1&lt;/h1&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string htmlStringPractice1 {
            get {
                return ResourceManager.GetString("htmlStringPractice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=UTF-8&quot; http-equiv=&quot;content-type&quot;&gt;
        ///    &lt;style&gt;
        ///      img {
        ///  		width:70%;
        ///
        ///        text-align: center;
        ///  		height:auto;
        ///			}
        ///      p,h1,h2
        ///      {
        ///        font-family: Cambria;
        ///      }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;navigation astronomique pratique&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1&gt;La navigation astronomique - Practice - Part 2&lt;/h1&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string htmlStringPractice2 {
            get {
                return ResourceManager.GetString("htmlStringPractice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=UTF-8&quot; http-equiv=&quot;content-type&quot;&gt;
        ///    &lt;style&gt;
        ///      img {
        ///  		width:70%;
        ///
        ///        text-align: center;
        ///  		height:auto;
        ///			}
        ///      p,h1,h2
        ///      {
        ///        font-family: Cambria;
        ///      }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;navigation astronomique theorie&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1&gt;La navigation astronomique - Theory - Part 1&lt;/h1&gt;
        ///    &lt;p&gt;La navigation astronomique est l’art de déterminer sa position
        ///      géographique par l’o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string htmlStringTheory1 {
            get {
                return ResourceManager.GetString("htmlStringTheory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=UTF-8&quot; http-equiv=&quot;content-type&quot;&gt;
        ///    &lt;style&gt;
        ///      img {
        ///  		width:70%;
        ///			text-align: center;
        ///  		height:auto;
        ///			}
        ///      p,h1,h2
        ///      {
        ///        font-family: Cambria;
        ///      }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;navigation astronomique theorie&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1&gt;La navigation astronomique - Theory - Part 2&lt;/h1&gt;
        ///    &lt;h2&gt;Calcul de la position&lt;/h2&gt;
        ///    Trois hauteurs ou plus permettent donc de tracer des cercles don [rest of string was truncated]&quot;;.
        /// </summary>
        public static string htmlStringTheory2 {
            get {
                return ResourceManager.GetString("htmlStringTheory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theory_fr.html.
        /// </summary>
        public static string htmlTheory1 {
            get {
                return ResourceManager.GetString("htmlTheory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        public static string part1 {
            get {
                return ResourceManager.GetString("part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        public static string part2 {
            get {
                return ResourceManager.GetString("part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string practice {
            get {
                return ResourceManager.GetString("practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizz.
        /// </summary>
        public static string quizz {
            get {
                return ResourceManager.GetString("quizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q1.
        /// </summary>
        public static string quizzPractice1Q1 {
            get {
                return ResourceManager.GetString("quizzPractice1Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q1 bad answer 1.
        /// </summary>
        public static string quizzPractice1Q1BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzPractice1Q1BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q1 bad answer 2.
        /// </summary>
        public static string quizzPractice1Q1BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzPractice1Q1BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q1 good answer.
        /// </summary>
        public static string quizzPractice1Q1GoodAnswer {
            get {
                return ResourceManager.GetString("quizzPractice1Q1GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q2 bad answer 1.
        /// </summary>
        public static string quizzPractice1Q2BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzPractice1Q2BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q2 bad answer 2.
        /// </summary>
        public static string quizzPractice1Q2BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzPractice1Q2BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q2 good answer.
        /// </summary>
        public static string quizzPractice1Q2GoodAnswer {
            get {
                return ResourceManager.GetString("quizzPractice1Q2GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q1.
        /// </summary>
        public static string quizzPractice2Q1 {
            get {
                return ResourceManager.GetString("quizzPractice2Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q1 bad answer 1.
        /// </summary>
        public static string quizzPractice2Q1BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzPractice2Q1BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q1 bad answer 2.
        /// </summary>
        public static string quizzPractice2Q1BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzPractice2Q1BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q1 good answer.
        /// </summary>
        public static string quizzPractice2Q1GoodAnswer {
            get {
                return ResourceManager.GetString("quizzPractice2Q1GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q2.
        /// </summary>
        public static string quizzPractice2Q2 {
            get {
                return ResourceManager.GetString("quizzPractice2Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q2 bad answer 1.
        /// </summary>
        public static string quizzPractice2Q2BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzPractice2Q2BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q2 bad answer 2.
        /// </summary>
        public static string quizzPractice2Q2BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzPractice2Q2BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 2 Q2 good answer.
        /// </summary>
        public static string quizzPractice2Q2GoodAnswer {
            get {
                return ResourceManager.GetString("quizzPractice2Q2GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice part 1 Q2.
        /// </summary>
        public static string quizzPracticeQ2 {
            get {
                return ResourceManager.GetString("quizzPracticeQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu&apos;est-ce que la hauteur d’un astre ?.
        /// </summary>
        public static string quizzTheory1Q1 {
            get {
                return ResourceManager.GetString("quizzTheory1Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La distance entre la verticale de l’astre et le pôle Nord.
        /// </summary>
        public static string quizzTheory1Q1BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzTheory1Q1BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’angle entre le cercle de hauteur et l’observateur.
        /// </summary>
        public static string quizzTheory1Q1BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzTheory1Q1BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’angle entre l’astre et l’horizon au point d’observation.
        /// </summary>
        public static string quizzTheory1Q1GoodAnswer {
            get {
                return ResourceManager.GetString("quizzTheory1Q1GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le rayon du cercle de hauteur est :.
        /// </summary>
        public static string quizzTheory1Q2 {
            get {
                return ResourceManager.GetString("quizzTheory1Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to égal à la hauteur de l&apos;astre.
        /// </summary>
        public static string quizzTheory1Q2BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzTheory1Q2BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne dépend pas de la hauteur de l&apos;astre.
        /// </summary>
        public static string quizzTheory1Q2BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzTheory1Q2BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to égal à 90° - h.
        /// </summary>
        public static string quizzTheory1Q2GoodAnswer {
            get {
                return ResourceManager.GetString("quizzTheory1Q2GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laquelle de ces affirmations est vraie ?.
        /// </summary>
        public static string quizzTheory2Q1 {
            get {
                return ResourceManager.GetString("quizzTheory2Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deux hauteurs au minimum sont nécessaires pour calculer un point.
        /// </summary>
        public static string quizzTheory2Q1BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzTheory2Q1BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il n’est pas possible de calculer un point en observant le Soleil seul.
        /// </summary>
        public static string quizzTheory2Q1BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzTheory2Q1BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour le calcul d’un point, les hauteurs peuvent être mesurées à des instants différents.
        /// </summary>
        public static string quizzTheory2Q1GoodAnswer {
            get {
                return ResourceManager.GetString("quizzTheory2Q1GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parmi les incertitudes qui suivent, laquelle sera prépondérante sur le calcul du point en Méditerranée ?.
        /// </summary>
        public static string quizzTheory2Q2 {
            get {
                return ResourceManager.GetString("quizzTheory2Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1 minute d’arc sur la mesure de hauteur de l’astre.
        /// </summary>
        public static string quizzTheory2Q2BadAnswer1 {
            get {
                return ResourceManager.GetString("quizzTheory2Q2BadAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.03 secondes d’arc sur le calcul d’éphéméride de l’astre.
        /// </summary>
        public static string quizzTheory2Q2BadAnswer2 {
            get {
                return ResourceManager.GetString("quizzTheory2Q2BadAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 secondes sur la mesure de l’heure.
        /// </summary>
        public static string quizzTheory2Q2GoodAnswer {
            get {
                return ResourceManager.GetString("quizzTheory2Q2GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good!.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theory.
        /// </summary>
        public static string theory {
            get {
                return ResourceManager.GetString("theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong....
        /// </summary>
        public static string wrong {
            get {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
    }
}
